export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const ADD_SALES_SUCCESS = 'ADD_SALES_SUCCESS';
export const ADD_SALES_ERROR = 'ADD_SALES_ERROR';
export const UPDATE_SALES_SUCCESS = 'UPDATE_SALES_SUCCESS';
export const UPDATE_SALES_ERROR = 'UPDATE_SALES_ERROR';
export const REMOVE_SALES_SUCCESS = 'REMOVE_SALES_SUCCESS';
export const REMOVE_SALES_FAILED = 'REMOVE_SALES_FAILED';
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_ERROR = 'FETCH_SALES_ERROR';
export const FILTER_SALES = 'FILTER_SALES';

export const FETCH_MATERIAL_SUCCESS = 'FETCH_MATERIAL_SUCCESS';
export const FETCH_MATERIAL_ERROR = 'FETCH_MATERIAL_ERROR';
export const UPDATE_MATERIAL_SUCCESS = 'UPDATE_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_ERROR = 'UPDATE_MATERIAL_ERROR';
export const ADD_MATERIAL_SUCCESS = 'ADD_MATERIAL_SUCCESS';
export const ADD_MATERIAL_ERROR = 'ADD_MATERIAL_ERROR';
export const FILTER_MATERIAL = 'FILTER_MATERIAL';
export const REMOVE_MATERIAL_SUCCESS = 'REMOVE_MATERIAL_SUCCESS';
export const REMOVE_MATERIAL_FAILED = 'REMOVE_MATERIAL_FAILED';

export const ADD_CARRIER_SUCCESS = 'ADD_CARRIER_SUCCESS';
export const ADD_CARRIER_ERROR = 'ADD_CARRIER_ERROR';
export const UPDATE_CARRIER_SUCCESS = 'UPDATE_CARRIER_SUCCESS';
export const UPDATE_CARRIER_ERROR = 'UPDATE_CARRIER_ERROR';
export const FETCH_CARRIER_SUCCESS = 'FETCH_CARRIER_SUCCESS';
export const FETCH_CARRIER_ERROR = 'FETCH_CARRIER_ERROR';
export const FILTER_CARRIER = 'FILTER_CARRIER';
export const REMOVE_CARRIER_SUCCESS = 'REMOVE_CARRIER_SUCCESS';
export const REMOVE_CARRIER_FAILED = 'REMOVE_CARRIER_FAILED';

export const ADD_COOK_SUCCESS = 'ADD_COOK_SUCCESS';
export const ADD_COOK_ERROR = 'ADD_COOK_ERROR';
export const UPDATE_COOK_SUCCESS = 'UPDATE_COOK_SUCCESS';
export const UPDATE_COOK_ERROR = 'UPDATE_COOK_ERROR';
export const FETCH_COOK_SUCCESS = 'FETCH_COOK_SUCCESS';
export const FETCH_COOK_ERROR = 'FETCH_COOK_ERROR';
export const FILTER_COOK = 'FILTER_COOK';
export const REMOVE_COOK_SUCCESS = 'REMOVE_COOK_SUCCESS';
export const REMOVE_COOK_FAILED = 'REMOVE_COOK_FAILED';